name: SVMinecraftPlugin
version: 1.0
main: com.servermine.MainPlugin  # <--- AGORA APONTA DIRETAMENTE PARA com.servermine
author: Seu Nome / Nome da Equipe
description: Plugin base customizado para o servidor, contendo módulos como Loja, Objetivos e PainelHUD.
api-version: 1.20 # Mantenha a versão do Spigot/Paper que você está usando

commands:
	objetivos:
		description: Ver objetivos ativos e seu progresso
		usage: /<command> [progresso]
	loja:
		description: Comandos da loja (criar, abrir)
	recompensa:
		description: Recompensa diária (exemplo)
	vipset:
		description: Define VIP de um jogador (admin)
		usage: /vipset <player> <GUERREIRO|LORDE|MAGO|NORMAL>
		permission: vip.admin
	resgatavip:
		description: Resgatar recompensa semanal de VIP
	time:
		description: Entrar/selecionar time (COMETA/ECLIPSE)
	guilda:
		description: Gerenciar guildas (criar/entrar)

permissions:
  vip.admin:
    description: Permissão para usar /vipset (definir VIP de players)
    default: op
  loja.admin:
    description: Permissão para gerenciar lojas (futuro)
    default: op
  guilda.admin:
    description: Permissão para gerenciar guildas (futuro)
    default: op